# Find AMD Display Library (ADL)
# Once done this will define
# ADL_FOUND
# ADL_LIBRARY
# ADL_INCLUDE_DIR
# Glaucous 2011 <glakke1 at gmail dot com>

FIND_PATH(
ADL_INCLUDE_DIR

NAMES
adl_sdk.h
ADL/adl_sdk.h
adl/adl_sdk.h

PATHS
${CMAKE_SOURCE_DIR}
${CMAKE_SOURCE_DIR}/src

DOC
"Directory where adl_sdk.h resides"
)

FIND_LIBRARY(
ADL_LIBRARY

NAMES
atiadlxx

PATHS
/usr/lib/fglrx

DOC
"ADL library location")

SET(ADL_FOUND "NO")
IF(ADL_LIBRARY AND ADL_INCLUDE_DIR)
	SET(ADL_FOUND "YES")
ENDIF()

IF(ADL_FIND_REQUIRED AND ADL_FOUND MATCHES "NO")
	MESSAGE(FATAL_ERROR "ADL required, but wasn't found.")
ENDIF()

IF(NOT ADL_FIND_QUIETLY)
	MESSAGE(STATUS "ADL FOUND: ${ADL_FOUND}")
	IF(ADL_FOUND MATCHES "YES")
		MESSAGE(STATUS ${ADL_INCLUDE_DIR})
		MESSAGE(STATUS ${ADL_LIBRARY})
	ENDIF()
ENDIF()
